apiVersion: 1

datasources:
  - name: InfluxDB-IoT
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iot
      defaultBucket: esp32
      tlsSkipVerify: true
    secureJsonData:
      token: dev-token-change-me
